### ISSUE TITLE
getFirehoseData silent defaults

### ISSUE THREAD

**Issue by aaronwolen** [mksamur/RTCGAToolbox#11]
There are a couple of cases where getFirehoseData() silently chooses among several candidate files for a particular data type. 

First, when data is available from both fresh and FFPE samples getFirehoseData() defaults to the non-FFPE file. I think that makes sense but should probably be documented somewhere.

Second, and more problematic, when data is available from both hi-seq and genome analyzer sequencers, the latter is selected. For example,

``` r
getFirehoseData("COAD", getFirehoseRunningDates(1), RNAseq2_Gene_Norm = TRUE)
```

downloads and imports data from `gdac.broadinstitute.org_COAD.Merge_rnaseqv2__**illuminaga**_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.Level_3.2015040200.0.0.tar.gz`, even though `gdac.broadinstitute.org_COAD.Merge_rnaseqv2__**illuminahiseq**_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.Level_3.2015040200.0.0.tar.gz` is also available. 

Is that intentional?

**Comment by mksamur** [comment]
that is actually not intentional let me think about it
