### ISSUE TITLE
inconsistencies between slot names and getFirehoseData arguments

### ISSUE THREAD

**Issue by lwaldron** [mksamur/RTCGAToolbox#13]
It's confusing and prone to user error, e.g. "Mutation" is the argument to getFirehoseData, but "Mutations" is the slot name and output of the show method of the FirehoseData class.

Marcel's extract() function uses the arguments to the getFirehoseData.  What do you think of changing the slot names to match these, before it makes it to release version?

Also - would sure be great to get the two RTCGAToolboxes synched up, especially to get the extract function from LiNk-NY/RTCGAToolbox into the main repo and into Bioconductor.  I'm teaching a workshop at Bioc2015 and will use the LiNk-NY version otherwise.

**Comment by LiNk-NY** [comment]
I've tried to work around this making every datatype lower case and taking out any underscores in the slotNames when matching the function arguments.

**Comment by lwaldron** [comment]
Ahh, I see that now, great idea Marcel.

**Comment by LiNk-NY** [comment]
I ended up using just a basic gsub of any input ending in "s"

**Comment by lwaldron** [comment]
Good workaround Marcel. I'm creating a vignette for the workshop that I'll push to your repo when done. 


By the way, congratulations on your new family member, Mehmet!





—
