### ISSUE TITLE
getFirehoseData error: Error in file(name, "wb")

### ISSUE THREAD

**Issue by cqneosun** [mksamur/RTCGAToolbox#22]
@mksamur
luscData = getFirehoseData (dataset="LUSC", runDate="20160128",gistic2_Date = "20160128",
+                              Clinic = TRUE, miRNASeq_Gene = TRUE,
+                             RNAseq2_Gene_Norm = TRUE, CNA_SNP = TRUE, CNV_SNP = TRUE,
+                             CNA_Seq = TRUE, CNA_CGH = TRUE, Methylation = TRUE,
+                             Mutation = TRUE, mRNA_Array = TRUE, miRNA_Array = TRUE,
+                             RPPA = TRUE,forceDownload = TRUE)

gdac.broadinstitute.org_LUSC.Merge_snp__genome_wide_snp_6__broad_mit_edu__Level_3__segmented_scna_minus_germline_cnv_hg19__seg.Level_3.2016012800.0.0.tar.gz
trying URL 'http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/LUSC/20160128/gdac.broadinstitute.org_LUSC.Merge_snp__genome_wide_snp_6__broad_mit_edu__Level_3__segmented_scna_minus_germline_cnv_hg19__seg.Level_3.2016012800.0.0.tar.gz'
Content type 'application/x-gzip' length 2298041 bytes (2.2 MB)
downloaded 2.2 MB

**Error in file(name, "wb") : cannot open the connection
In addition: Warning message:
In file(name, "wb") :
  cannot open file 'gdac.broadinstitute.org_LUSC.Merge_snp__genome_wide_snp_6__broad_mit_edu__Level_3__segmented_scna_minus_germline_cnv_hg19__seg.Level_3.2016012800.0.0/LUSC.snp__genome_wide_snp_6__broad_mit_edu__Level_3__segmented_scna_minus_germline_cnv_hg19__seg.seg.txt': No such file or directory**

**Comment by cqneosun** [comment]
gdac.broadinstitute.org_LUSC.Merge_methylation__humanmethylation27__jhu_usc_edu__Level_3__within_bioassay_data_set_function__data.Level_3.2016012800.0.0.tar.gzgdac.broadinstitute.org_LUSC.Merge_methylation__humanmethylation450__jhu_usc_edu__Level_3__within_bioassay_data_set_function__data.Level_3.2016012800.0.0.tar.gz
trying URL 'http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/LUSC/20160128/gdac.broadinstitute.org_LUSC.Merge_methylation__humanmethylation27__jhu_usc_edu__Level_3__within_bioassay_data_set_function__data.Level_3.2016012800.0.0.tar.gz'
Content type 'application/x-gzip' length 41288333 bytes (39.4 MB)
downloaded 8.0 MB

**Error in untar2(tarfile, files, list, exdir) : incomplete block on file
In addition: Warning message:
In download.file(url = fileLink, destfile = tcgafile, method = "auto",  :
  downloaded length 8413184 != reported length 41288333**

**Comment by cqneosun** [comment]
gdac.broadinstitute.org_LUSC.Merge_transcriptome__agilentg4502a_07_3__unc_edu__Level_3__unc_lowess_normalization_gene_level__data.Level_3.2016012800.0.0.tar.gz
trying URL 'http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/LUSC/20160128/gdac.broadinstitute.org_LUSC.Merge_transcriptome__agilentg4502a_07_3__unc_edu__Level_3__unc_lowess_normalization_gene_level__data.Level_3.2016012800.0.0.tar.gz'
Content type 'application/x-gzip' length 10429884 bytes (9.9 MB)
downloaded 9.9 MB

**Error in dirname(name) : path too long**

**Comment by cqneosun** [comment]
How to deal with these error?

**Comment by gy80** [comment]
Hi
I am wondering if you guys have solutions now to fix this issue! Thanks a lot!

**Comment by LiNk-NY** [comment]
See #19 
Closing this one
