### ISSUE TITLE
How to getData RAPP?

### ISSUE THREAD

**Issue by cqneosun** [mksamur/RTCGAToolbox#23]
getData(luscData,"RPPAArray" ,platform = NULL, CN = "All")
LUSC FirehoseData object
Available data types:
RPPAArray: A list contains FirehosemRNAArray object(s), length: 1
GISTIC: A FirehoseGISTIC object to store copy number data
Mutations: A data.frame, dim: 65305	86
To export data, you may use getData() function.
Error in .getListData(object@RPPAArray, platform) : Please set platform

getData(luscData,"RPPAArray")
LUSC FirehoseData object
Available data types:
RPPAArray: A list contains FirehosemRNAArray object(s), length: 1
GISTIC: A FirehoseGISTIC object to store copy number data
Mutations: A data.frame, dim: 65305	86
To export data, you may use getData() function.
Error in .getListData(object@RPPAArray, platform) : Please set platform

getData(luscData,"RPPAArray",RPPAArray)
LUSC FirehoseData object
Available data types:
RPPAArray: A list contains FirehosemRNAArray object(s), length: 1
GISTIC: A FirehoseGISTIC object to store copy number data
Mutations: A data.frame, dim: 65305	86
To export data, you may use getData() function.
Error in .getListData(object@RPPAArray, platform) : 
  object 'RPPAArray' not found

Where can I find the information of platform?

**Comment by LiNk-NY** [comment]
Hi @cqneosun, 

You can extract the data by assigning the expression to an object: 
```
rppa <- getData(luscData,"RPPAArray",RPPAArray)
```

You will always get the print out of the show method due to the underlying coding. 
We hope to get this fixed. 

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Hi @cqneosun,
Thank you for your report. I will look into this further.
The package has gone over considerable changes. Please let me know if this error persists. 
More updates to the package are coming soon!
Best regards,
Marcel
