### ISSUE TITLE
getDiffExpressedGenes  can not plot heatmap of all gene，because of the “limma“ package update.

### ISSUE THREAD

**Issue by cdy371761145** [mksamur/RTCGAToolbox#25]
Dear mksamur/RTCGAToolbox:
hi~
When I use the "getDiffExpressedGene" function to test the RTCGAToolbox ,like 
`diffGeneExprs <- getDiffExpressedGenes(dataObject=brcaData,DrawPlots=TRUE, adj.method="BH", adj.pval=0.05, raw.pval=0.05, logFC=2, hmTopUpN=100, hmTopDownN=100)`

I found the heatmap did not show all genes ，did not like the sample be given.
![image](https://user-images.githubusercontent.com/34931772/34430288-6b60461a-ec9e-11e7-982c-af945406f6c4.png)

So I check the code ,find the reason。
because of the [“limma“ package update 3.32.0](http://bioconductor.org/packages/devel/bioc/news/limma/NEWS),the function  length() methods has been removed,these  code in  "getDiffExpressedGene" function can not get the number of genes(but get the number of list components in the object ).
`o   length() methods removed all limma data objects (objects of class
	 EList, EListRaw, RGList, MAList or MArrayLM). length(x) will now
	 return the number of list components in the object rather than the
	 number of elements in the expression matrix.
`

`aradeger <- topTable(fit2, adjust.method = adj.method, 
                    genelist = fit$genes, number = length(fit2))`

Now,I solve by using limma 3.30，can plot the right heatmap and right result。

Is this the real error causes？if yes，can you solve this problem？(maybe use prod(dim(fit)) to replace  length(fit2)）
`sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.4
RTCGAToolbox_2.8.0`

Many thanks！
Dee Chen

PS.I'm a students,English is not very skilled ,If there is something wrong with the content or express, please understanding.

**Comment by LiNk-NY** [comment]
Hi @cdy371761145 
The maintainer of this package has transferred maintainership to me and I am deprecating the function in question due to difficulty in maintaining said functions. If you or someone you know would like to maintain the functions listed in the `NEWS.md` file. Please create another package that depends on this one.
Best,
Marcel
