### ISSUE TITLE
Error loading hg19.ucsc.gene.locations data

### ISSUE THREAD

**Issue by asmagen** [mksamur/RTCGAToolbox#26]
Hello,

The manual of the package mentions an object called 'hg19.ucsc.gene.locations' providing a mapping between gene symbols and chromosomes. However, the object is not loaded with the package and calling `data('hg19.ucsc.gene.locations')` doesn't work either:
```
> data('hg19.ucsc.gene.locations')
Warning message:
In data("hg19.ucsc.gene.locations") :
  data set ‘hg19.ucsc.gene.locations’ not found
```

How can I obtain the file?

Thanks,
Assaf

**Comment by LiNk-NY** [comment]
Hi Assaf, @asmagen 
Try using `BiocManager::available` to look for a package that matches what you're looking for. 
There is also the http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData page for data experiment packages.
Best,
Marcel
