### ISSUE TITLE
mirSeqData

### ISSUE THREAD

**Issue by fk506cni** [mksamur/RTCGAToolbox#28]
hi

I used RTCGAToolbox and get  COLREAD mirRNAseq data.
I found that getData function return "Read count" data. not "reads_per_million_miRNA_mapped".

I wonder "read count" is not suitable for comparing the one gene expression level among many sample.
Or, is should be annotated that value is not normalized?

thank you.

**Comment by LiNk-NY** [comment]
Hi unkodaisuki, @fk506cni 
Please ask your question on the Bioconductor support site https://support.bioconductor.org
If you'd like to have getFirehoseData support an additional dataset, please follow the steps taken by Matt https://github.com/mksamur/RTCGAToolbox/issues/39 to report and create a PR for the feature. 
Best,
Marcel
