### ISSUE TITLE
RaggedExperiment

### ISSUE THREAD

**Issue by Akyanus** [mksamur/RTCGAToolbox#31]
Hi,

I tried to install RTCGAToolbox with devtools. I use R version Version 1.2.1335.

but I have this error:

Rd warning: C:/Users/didem/AppData/Local/Temp/RtmpgbAypF/R.INSTALL28fc223c7ee6/RTCGAToolbox/man/biocExtract.Rd:32: file link 'RaggedExperiment' in package 'RaggedExperiment' does not exist and so has been treated as a topic

then, I tried to install 'RaggedExperiment' package, but this issue didin't change. Can you help for this?

**Comment by LiNk-NY** [comment]
Hi Akyanus, @Akyanus 
The R version you are reporting seems off to me. Please use a more recent version of R (at least 3.5).
Also, make sure that you have `RaggedExperiment` installed. 

Best regards,
Marcel

**Comment by Akyanus** [comment]
Hi,

I installed this first :
library("devtools") # You should install devtools package before loading it.
> install_github("mksamur/RTCGAToolbox

Then I had this error. After that I installed RaggedExperiment. But this issue didn't change

I remove R completely, I installed again. I have same problem .

**Comment by LiNk-NY** [comment]
Hi Akyanus, @Akyanus 
Why don't you use `BiocManager`? 
You can follow the installation instructions here: 
https://bioconductor.org/packages/RTCGAToolbox

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("RTCGAToolbox")
```

Without a _fully_ reproducible example, I am unable to identify
the issue and help you. I can only guess that you have 'warnings as errors'
enabled somewhere. You can try `options(warn = 0)`.

Best regards,
Marcel

**Comment by Akyanus** [comment]
I use tcgabiolinks, too. When rtcgatoolbox package was installed, there were alot of error. Now Tcgabiolinks is not working and summerizeexperiment, too.  these are big problem. My system was down. Also I tried this installation. I dont understand now, I will try to reinstall R again. I will write you again.

**Comment by LiNk-NY** [comment]
@Akyanus 
To avoid issues like this, I would definitely recommend using the Bioconductor docker containers. 
See this page here to get started: https://www.bioconductor.org/help/docker/

The docker containers avoid you the struggles with system set up by providing a containerized environment for running R and Bioconductor. 

Best,
Marcel

**Comment by Akyanus** [comment]
Hi,

 installed RTCGAToolbox, but some commands are not working.

for example

`library(RTCGAToolbox)
# Download GISTIC results
lastAnalyseDate <- getFirehoseAnalyzeDates(1)
gistic <- getFirehoseData("LUSC",gistic2_Date = lastAnalyseDate)
gistic.allbygene <- getData(gistic,type = "GISTIC", platform = )
gistic.allbygene <- gistic.allbygene[1:10,]
gistic.thresholedbygene <- getData(gistic,type = "GISTIC", CN = "Thresholed")
gistic.thresholedbygene <- gistic.thresholedbygene[1:10,]
save(gistic.allbygene,gistic.thresholedbygene,file = "GBMGistic.rda", compress = "xz")`

there is an error:

> gistic.allbygene <- getData(gistic,type = "GISTIC", CN = "All")
Error in getData(gistic, type = "GISTIC", CN = "All") : 
  unused argument (CN = "All")

**Comment by LiNk-NY** [comment]
Please update your version of `RTCGAToolbox`.

**Comment by LiNk-NY** [comment]
Actually this is stale code provided by `TCGAWorkflowData`. Please post this on the support site and tag `TCGAWorkflowData`

**Comment by LiNk-NY** [comment]
@Akyanus 
I've created a pull request in the workflow here: BioinformaticsFMRP/TCGAWorkflowData#1
That should fix the issues you're having. Please use that code moving forward.

Please create another issue if you're still having problems and _please_ 
provide a fully reproducible example.

Best regards,
Marcel
