### ISSUE TITLE
Move can evolve path to GitHub for cohort and date info

### ISSUE THREAD

**Issue by mksamur** [mksamur/RTCGAToolbox#32]
http connections going to following URLs will be replaced
http://www.canevolve.org/fmineRgistic.txt
http://www.canevolve.org/fmineRdate.txt
http://www.canevolve.org/fmineRdataset.txt

**Comment by mksamur** [comment]
new URLs will be

https://raw.githubusercontent.com/mksamur/RawDataURLs/master/fmineRdataset.txt
https://raw.githubusercontent.com/mksamur/RawDataURLs/master/fmineRdate.txt
https://raw.githubusercontent.com/mksamur/RawDataURLs/master/fmineRgistic.txt

**Comment by LiNk-NY** [comment]
Hi Mehmet, @mksamur 

There is still 
```r
asd = read.csv(url(paste0("http://www.canevolve.org/fmineRgetSize.php?url=",dataURL)))
```

What can be done for that URL? 

Best, 
Marcel

**Comment by LiNk-NY** [comment]
These files don't have to be online. They can be added to a small internal database.

**Comment by LiNk-NY** [comment]
See 16a55282a8fd8ff41963ecbdc0eb314622d85cda

**Comment by mksamur** [comment]
Thx for the code base update.
Yes, these can be offline doesn't have to be online but the idea was to provide update at any second when there is a new release. It should be all set with your changes now. I wanted to break the canevolve.org connection as I may retire the canevolve.

**Comment by mksamur** [comment]
We have one more canevolve.org connection in the `.checkFileSize` function. Should we disable this file size check too?

**Comment by LiNk-NY** [comment]
I think the `.checkFileSize` is called when using the main data download functions. It would be good to keep it for now until I can work on a getting a file size from URL query. 
Thanks Mehmet.
-Marcel

**Comment by mksamur** [comment]
we can use HEAD function from httr library and replace it as: 

.checkFileSize <- function(dataURL,fileSizeLimit)
{
  fileSize <- HEAD(dataURL)
  fileSize <- as.numeric(fileSize$headers$`content-length`)/1e6 # this should convert file size from byte to MB 
  if (fileSize > fileSizeLimit) {
    message(dataURL)
    message(paste("File Size: ~"), fileSize,"MB")
    message("File above won't be downloaded due to data size, RTCGAToolbox will skip this data!")
    return(FALSE)
  } else {
    return(TRUE)
  }

}
