### ISSUE TITLE
obtain the expression data in unit TPM

### ISSUE THREAD

**Issue by dingying85** [mksamur/RTCGAToolbox#35]
Hi,

Is there a way to obtain the gene expression data in unit TPM instead of normalized counts? Thanks.

**Comment by LiNk-NY** [comment]
Hi,
Thank you for your question. 
You should be able to get `TPM` data from the `RNASeqGene = TRUE` flag.
For example:
```r
getFirehoseData("COAD", RNASeqGene = TRUE, clinical = FALSE)
```
This will download `gdac.broadinstitute.org_COAD.Merge_rnaseq__illuminaga_rnaseq__unc_edu__Level_3__gene_expression__data.Level_3.2016012800.0.0.tar.gz`

Please check GDAC Firehose documentation to be sure. 
I will add this to the documentation. It seems to be missing. 
Thanks.

**Comment by mherberg** [comment]
Is the non-normalized TPM data in "rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes__data.Level_3" or in "rnaseq__illuminaga_rnaseq__unc_edu__Level_3__gene_expression__data.Level_3".

When I download using RNASeqGene = TRUE I get less specimens then I do with the normalized data, which should not be the case.

**Comment by LiNk-NY** [comment]
> Is the non-normalized TPM data in "rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes__data.Level_3" or in "rnaseq__illuminaga_rnaseq__unc_edu__Level_3__gene_expression__data.Level_3".

It's the second option `illuminaga_rnaseq_*`. 

> When I download using RNASeqGene = TRUE I get less specimens then I do with the normalized data, which should not be the case.

Perhaps you're thinking of `RNASeq2GeneNorm`?
