### ISSUE TITLE
Exported expression matrix from firehose looks empty - DEG analysis

### ISSUE THREAD

**Issue by Hulkk3000** [mksamur/RTCGAToolbox#38]
Hello,

I am currently using the RTCGAToolbox with my current version of R (R version 4.0.2 (2020-06-22)) together with R Studio (Version 1.3.1056).

As I am completely new to this, I tried to first copy and understand the example code given in the manual. The code runs fine for me with the example data set when it comes to **DEG analysis**. 

Here is the code I run inside of R Studio:

`# Differential gene expression analysis for gene level RNA data.`
`diffGeneExprs <- getDiffExpressedGenes(dataObject=RTCGASample, DrawPlots=TRUE,
                                       adj.method="BH", adj.pval=0.05, raw.pval=0.05, logFC=2, hmTopUpN=10,
                                       hmTopDownN=10)`

But as soon as I try to download some _real data_ from firehose I get stuck with the following **error**:

`Error in if (dim(dataObject@RNASeq2GeneNorm)[1] > 0 & dim(dataObject@RNASeq2GeneNorm)[2] >  : 
  argument is of length zero`

That's the code before the error plus output:

`#load RCTGToolbox package
library(RTCGAToolbox)`
`brcaData <- getFirehoseData (dataset="BRCA",forceDownload=TRUE, runDate="20140416", gistic2Date="20140115", clinic=TRUE, RNAseqGene=TRUE, mRNAArray=TRUE, Mutation=TRUE)`

> gdac.broadinstitute.org_BRCA.Clinical_Pick_Tier1.Level_4.2014041600.0.0.tar.gz
trying URL 'http://gdac.broadinstitute.org/runs/stddata__2014_04_16/data/BRCA/20140416/gdac.broadinstitute.org_BRCA.Clinical_Pick_Tier1.Level_4.2014041600.0.0.tar.gz'
Content type 'application/x-gzip' length 339869 bytes (331 KB)
==================================================
downloaded 331 KB

>gdac.broadinstitute.org_BRCA.Clinical_Pick_Tier1.Level_4.2014041600.0.0
>gdac.broadinstitute.org_BRCA.Merge_transcriptome__agilentg4502a_07_3__unc_edu__Level_3__unc_lowess_normalization_gene_level__data.Level_3.2014041600.0.0.tar.gz

>trying URL 'http://gdac.broadinstitute.org/runs/stddata__2014_04_16/data/BRCA/20140416/gdac.broadinstitute.org_BRCA.Merge_transcriptome__agilentg4502a_07_3__unc_edu__Level_3__unc_lowess_normalization_gene_level__data.Level_3.2014041600.0.0.tar.gz'
Content type 'application/x-gzip' length 38892970 bytes (37.1 MB)
==================================================
downloaded 37.1 MB

>gdac.broadinstitute.org_BRCA.Merge_transcriptome__agilentg4502a_07_3__unc_edu__Level_3__unc_lowess_normalization_gene_level__data.Level_3.2014041600.0.0
mRNAArray data will be imported! This may take a while!
Start: 2020-08-10 18:03:52
Done: 2020-08-10 18:03:56
gdac.broadinstitute.org_BRCA.Mutation_Packager_Calls.Level_3.2014041600.0.0.tar.gz
trying URL 'http://gdac.broadinstitute.org/runs/stddata__2014_04_16/data/BRCA/20140416/gdac.broadinstitute.org_BRCA.Mutation_Packager_Calls.Level_3.2014041600.0.0.tar.gz'
Content type 'application/x-gzip' length 10453937 bytes (10.0 MB)
==================================================
downloaded 10.0 MB

>There were 50 or more warnings (use warnings() to see the first 50)

`# Differential gene expression analysis for gene level RNA data.`
`# Heatmaps are given below.`
`diffGeneExprs <- getDiffExpressedGenes(dataObject=brcaData, DrawPlots=TRUE, adj.method="BH", adj.pval=0.05, raw.pval=0.05, logFC=2, hmTopUpN=100, hmTopDownN=100)`

This call for `getDiifExpressedGenes`produces the error from above for me:

>`Error in if (dim(dataObject@RNASeq2GeneNorm)[1] > 0 & dim(dataObject@RNASeq2GeneNorm)[2] >  : 
  argument is of length zero`

I checked the warning messages given, which are all the same from 1-50:

`warnings()`
`Warning messages:`
`1: In apply(tmpMat, 2, as.numeric) : NAs introduced by coercion`

I already tried with different data which I download manually and got the same error message.

I also installed R and R Studio completely fresh in my OSX system, but it didn't help.
One thing I did since I got the following error message while always downloading data from firehose:

>tar: Failed to set default locale

That's why I did run the following in my terminal:

`defaults write org.R-project.R force.LANG en_US.UTF-8` 

to force and set the language, which seems to help my problem, since then I didn't get anymore errors like that.

If someone can help me with my current problem that I am having I would be very happy. If you need more code I ran or information to help solve this issue, just let me know.

Thank you very much in advance,
Hulkk3000 
![PVC-00815---F](https://user-images.githubusercontent.com/69472529/89806852-f21ea400-db37-11ea-8539-b4466259f514.png)

**Comment by LiNk-NY** [comment]
Hi Hulk @Hulkk3000 
Nice to see that you are using `RTCGAToolbox`. 
It looks like you should be setting the `RNASeq2GeneNorm` to `TRUE`.

```
    brcaData <- getFirehoseData(
        dataset="BRCA", forceDownload=TRUE,
        runDate="20140416", gistic2Date="20140115", clinic=TRUE,
        RNAseqGene=TRUE, mRNAArray=TRUE, Mutation=TRUE,
        RNASeq2GeneNorm = TRUE
    )
```
I tried to run the `getDiffExpressedGenes` function but it was not working due to a bug. 
I currently am tied up in other projects to debug this but I would happily accept a PR. 

I am sure there are many alternative tools available for analyzing the data in Bioconductor.

Best,
Marcel

**Comment by Hulkk3000** [comment]
Hi Marcel @LiNk-NY 

Thanks for your reply and suggestions. I tried setting `RNASeq2GeneNorm` to `TRUE`. This helped a little bit as you said. It downloaded the needed files but I also got stuck again when I tried to run the `getDiffExpressedGenes`, same as you :(

I am currently looking, as to your suggestion, into other tools to analyse the data. If you have any recommendations for me, which tool/package to look into from Bioconductor please let me know here or PM me :)

Best,
Johannes @Hulkk3000 
![PVC-00815---F](https://user-images.githubusercontent.com/69472529/90335375-eec26700-dfd4-11ea-8cf2-a80251a40319.png)

**Comment by Hulkk3000** [comment]
Hi Marcel @LiNk-NY ,

Also wanted to ask what this means:
> I tried to run the `getDiffExpressedGenes` function but it was not working due to a bug.
> I currently am tied up in other projects to debug this but I would happily accept a PR.

I am new to GitHub and was curious what PR means in this context?

Best,
Johannes @Hulkk3000 
![PVC-00815---F](https://user-images.githubusercontent.com/69472529/90412952-1cc7aa00-e0ae-11ea-8dd2-11a51ad41a12.png)

**Comment by LiNk-NY** [comment]
Hi Johannes, @Hulkk3000 
A PR is a pull request that provides a fix / enhancement to existing code. 
See more here: 
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
https://docs.github.com/en/github/getting-started-with-github/github-glossary#pull-request

This may help with your second question: 
https://www.bioconductor.org/packages/devel/workflows/vignettes/rnaseqGene/inst/doc/rnaseqGene.html

Best,
Marcel

**Comment by Hulkk3000** [comment]
Hey Marcel @LiNk-NY,

thanks for explaining it to me and providing me with some further information to read more about it 👍

Also thanks for giving me a useful hint regarding my second question :) Much appreciated!

If I can be  of any help I let you know. But I am also fairly new to the world of R programming.

Best,
Johannes @Hulkk3000 
![small_hulk_fist](https://user-images.githubusercontent.com/69472529/90567814-0a7f6600-e1ab-11ea-9a2d-955a51647205.png)

**Comment by LiNk-NY** [comment]
**Update**: This function is deprecated for the next release. Please see one of the many workflows in Bioconductor for differential expression.
