### ISSUE TITLE
RNASeqV2 raw count and scaled estimate (TPM) download

### ISSUE THREAD

**Issue by mherberg** [mksamur/RTCGAToolbox#39]
See https://github.com/waldronlab/curatedTCGAData/issues/38 for background.

I have modified RTCGAToolbox to add on the download of RNASeqV2 raw count and scaled estimate data. I have only changed the RTCGAToolbox-Class and getFirehoseData and none of the other functions .

https://github.com/mherberg/RTCGAToolbox

**Comment by LiNk-NY** [comment]
It should be taken care of in e56ef2400c1bad1194555612d70219fb95687734
Thanks!
