### ISSUE TITLE
data set downloading error.

### ISSUE THREAD

**Issue by ffeng23** [mksamur/RTCGAToolbox#43]
Running the example code to download data set returns an error.
brcaData <- getFirehoseData(dataset="READ", runDate="20160128",
    forceDownload=TRUE, clinical=TRUE, Mutation=FALSE)
Error in UseMethod("xmlNamespaceDefinitions") : 
  no applicable method for 'xmlNamespaceDefinitions' applied to an object of class "NULL"

**Comment by ffeng23** [comment]
It was not an issue now. This was because the firehose data server was offline. The server is back online now.

**Comment by LiNk-NY** [comment]
Thanks for reporting back!
