### ISSUE TITLE
New Issue with getFirehoseData

### ISSUE THREAD

**Issue by biostars-nyc** [mksamur/RTCGAToolbox#44]
I've been using this exact command for months with no issue, but suddenly produces the error below.

Error in UseMethod("xmlNamespaceDefinitions") : 
  no applicable method for 'xmlNamespaceDefinitions' applied to an object of class "NULL"

Code:
```r
library(RTCGAToolbox)
ov <- getFirehoseData(
     dataset = 'OV',
     runDate = "20120306",
     clinical = TRUE,
     forceDownload = TRUE,
     destdir = getwd(),
     fileSizeLimit = 500)
```

**Comment by LiNk-NY** [comment]
I can't reach http://gdac.broadinstitute.org/runs/stddata__2012_03_06/data/OV/20120306/ and it looks like gdac.broadinstitute.org is down. 
Best,
Marcel

**Comment by LiNk-NY** [comment]
It looks like the gdac page has changed. I've updated the code to make use of this new layout. 
9118e046ffe371398ae10205346d4cc83189dcbe
-MR
