### ISSUE TITLE
UUID - barcode converter

### ISSUE THREAD

**Issue by lwaldron** [mksamur/RTCGAToolbox#6]
A function to translate any UUID to barcode and vice-versa would be great.

**Comment by ttriche** [comment]
https://github.com/uscepigenomecenter/EGC.tools/blob/recovery/R/getBarcodes.R

https://github.com/uscepigenomecenter/EGC.tools/blob/recovery/R/getUUIDs.R



Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

**Comment by mksamur** [comment]
Hi all:
I have implemented the code but on the web service part there is a limit for query. I need to find a way to pass if for large datasets.

**Comment by ttriche** [comment]
Ask the DCC folks not to throttle so goddamned much

**Comment by mksamur** [comment]
I pushed a new version "getFirehoseData" function now has new parameter "getUUIDs". By default it is FALSE for now but if you make it T then it gets UUIDs for all barcodes that are in data objects.

For query limit, I'm using a waiting period with is not a good idea but solves the problem for now, mean time I can try to contact with DCC

Tim, thanks for your tip on code.

**Comment by ttriche** [comment]
No problem, it was my code... Just had to figure out where I left it ;-)
