### ISSUE TITLE
getFirehoseData creating blank object

### ISSUE THREAD

**Issue by LiNk-NY** [mksamur/RTCGAToolbox#7]
Hi Mehmet,
I tried to create a data set object using 
a2 <- getFirehoseData(dataset="BRCA", runDate="20140416",gistic2_Date="20140115", RNAseq_Gene=TRUE,Clinic=TRUE,mRNA_Array=TRUE,Mutation=TRUE)
but only got a blank object in return. 

Object of class "data.frame"
data frame with 0 columns and 0 rows

Is something wrong with the links or the download function? 
I'll keep looking into it. 
Thanks, 
MR

**Comment by mksamur** [comment]
Seems like there is something wrong with connection!I'm gonna take a look

**Comment by mksamur** [comment]
I guess there is an update on portal and parser does not work like how it
suppose to be, I will try to find a solution

**Comment by mksamur** [comment]
Issue has been solved! Please use the latest version! There was an update on Firehose which effected the links!
