### ISSUE TITLE
Read local data

### ISSUE THREAD

**Issue by LiNk-NY** [mksamur/RTCGAToolbox#8]
Hi Mehmet, 
The getFirehoseData function should read files from the local directory, perhaps that can be part of the exportFiles function?

**Comment by mksamur** [comment]
Hi Marcel:
If you have a data on your working directory that points the same dataset
and date it actually reads it from there unless you won't force to download
it with "forceDownload". Is what you are asking different than this?
Best,
Mehmet

**Comment by LiNk-NY** [comment]
Yes, I see that it is supposed to read files from your working directory although, I keep getting seeing the message: 

gdac.broadinstitute.org_OV.Clinical_Pick_Tier1.Level_4.2014120600.0.0.tar.gz

when running: 
ov <- getFirehoseData("OV", runDate="20141206", Clinic = TRUE, forceDownload = FALSE, getUUIDs = FALSE)

which would mean that it is downloading the file because this message output is in the exportFiles function as "message(delFodler)" 

Correct me if this is wrong. 

Regards,
Marcel

**Comment by mksamur** [comment]
Yep it still put messages on system out but it reads from directory. It
seems confusing you are right. I can change the messages.

**Comment by LiNk-NY** [comment]
Thank you Mehmet.
