### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by LiNk-NY** [mksamur/RTCGAToolbox#9]
I'm getting the error message : 
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") : unable to connect to 'www.canevolve.org' on port 80.

**Comment by mksamur** [comment]
This looks OK on my test environment. And server is up. Could you please
check this again? I will move http connections on to another server or my
be github later for more stable environment.

**Comment by LiNk-NY** [comment]
That's interesting, it's working now. Thank you.
